In [1]:
import cv2

# 默认读取格式 - BGR
img = cv2.imread("./data/images/2024-03-28_23-34.png")

# 获取灰度图片
img_gray = cv2.imread("./data/images/2024-03-28_23-34.png", cv2.IMREAD_GRAYSCALE)


In [2]:
print(img)
type(img)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[237 231 228]
  [237 231 228]
  [237 231 228]
  ...
  [237 231 228]
  [237 231 228]
  [237 231 228]]

 [[237 231 228]
  [237 231 228]
  [237 231 228]
  ...
  [237 231 228]
  [237 231 228]
  [237 231 228]]

 [[237 231 228]
  [237 231 228]
  [237 231 228]
  ...
  [237 231 228]
  [237 231 228]
  [237 231 228]]]


numpy.ndarray

In [3]:
img.shape

(1200, 2022, 3)

In [4]:
# 展示图片
cv2.imshow("image", img)

cv2.imshow("image_gray", img_gray)

# 等待时间，毫秒级，0 便是任意键终止
cv2.waitKey(0)
# 关闭所有窗口
cv2.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/arch/.pyenv/versions/3.11.8/envs/opencv/lib/python3.11/site-packages/cv2/qt/plugins"
QFont::fromString: Invalid description 'MiSans,10,-1,5,383,0,0,0,0,0,0,0,0,0,0,1,Medium'
QFont::fromString: Invalid description 'Fira Code,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'MiSans,10,-1,5,383,0,0,0,0,0,0,0,0,0,0,1,Medium'
QFont::fromString: Invalid description 'MiSans,10,-1,5,383,0,0,0,0,0,0,0,0,0,0,1,Medium'


In [5]:
# 保存图片
cv2.imwrite("./data/images/截图-gray.png", img_gray)

True